[package]
name = "solar_dawn_common"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.9.1" }
serde = { version = "1.0.219", features = ["derive", "rc"] }

[features]
server = []
client = []
