name: Build
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tooling
        run: |
          cargo install cargo-binstall
          cargo binstall dioxus-cli

      - name: Lint
        run: cargo clippy --verbose

      - name: Test
        run: cargo test --verbose

      - name: Package
        run: dx bundle --platform web --package solar_dawn_client
